### ISSUE TITLE
Audio is disabled?

### ISSUE THREAD

**Issue by AeSix** [flaiker/bottimus#17]
java.lang.UnsupportedOperationException: Sorry! Audio is disabled due to an internal JDA error! Contact Dev!
        at net.dv8tion.jda.managers.AudioManager.openAudioConnection(AudioManager.java:76)
        at com.flaiker.bottimus.services.AudioService.init(AudioService.java:83)
        at com.flaiker.bottimus.listeners.CommandListener.onGuildMessageReceived(CommandListener.java:49)
        at net.dv8tion.jda.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:140)
        at net.dv8tion.jda.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:54)
        at net.dv8tion.jda.handle.MessageReceivedHandler.handle(MessageReceivedHandler.java:45)
        at net.dv8tion.jda.requests.WebSocketClient.onTextMessage(WebSocketClient.java:153)
        at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:233)
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:211)
        at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:910)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:693)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:102)
        at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:61)

Obviously this is saying audio is disabled. I would like to be able to run this on my VM which has no audio software, or hardware, other than VLC. I'm tired of python bots crashing every ten minutes (Seriously, did they steal code from Windows ME?) and I can't for the life of me get anything else to run. I seen this bot today and was really hoping that it would work, especially as it uses VLC (LOVE IT! Been a VLC user since around 03 I believe!)  Anyways, any help would really be appreciated! :)

**Comment by fabianlupa** [comment]
What kind of virtual machine are you using (OS, version)?
I just tested it on my Ubuntu 14.04 (server edition) virtual server and it is working just fine.

**Comment by AeSix** [comment]
Digital Ocean
512 MB Memory / 20 GB Disk  - Ubuntu 15.10 x32
This is a single core, single thread VM. 
This is completely headless, no X environment, etc.

**Comment by fabianlupa** [comment]
Does it work locally on your pc?

One thing to keep in mind is that the bot cannot join the voice channel by itself. You have to login as the bot user, join the guild/server and the voice channel you want it to operate in. Then logout and start the jar after adjusting the configuration file.
I just thought leaving out the manual-voice-channel-joining part might throw a similar error.

If that however is not the problem I'll look into setting up 15.10x32 vm to reproduce the error.

**Comment by AeSix** [comment]
Hi, I will be testing this in the next day or so.  However, the error appeared to be due to lack of ability to operate on a system without any audio service.  Additionally, my "test" system will not be in any way similar to the production system I am hoping to use (The one mentioned above), as I will be using a Windows 10 desktop for testing. 

I'm sorry for not having been able to allocate time to test previous to now, I'll let you know as soon as I know anything different!

**Comment by fabianlupa** [comment]
I am just asking because my server is running headless as well with no physical or virtual audio device I would be aware of. So I guess my question is if you can get it to run on any system at all.
